### ISSUE TITLE
local FragFold

### ISSUE THREAD

**Issue by adelakun2** [swanss/FragFold#1]
How do one run FragFold locally?

**Comment by swanss** [comment]
Hi! Sorry for the delay in response. 

If you're still interested in this, could you please explain your use case a little more? It would be easy for me to add an option to loop over the colabfold jobs sequentially. Depending on your GPU set-up, you may have access to multiple, in which case it would be better run multiple colabfold jobs in parallel.

Edit: I've added a new [branch](https://github.com/swanss/FragFold/tree/nextflow) with support for local execution using nextflow. Let me know if you're interested in trying this.
