### ISSUE TITLE
Assistance Required with FragFold Installation

### ISSUE THREAD

**Issue by nd346** [swanss/FragFold#5]
Hi,

I am currently facing some challenges installing FragFold on my machine/cluster and would greatly appreciate your guidance on this matter. I've noticed the installation consistently fails, possibly related to how the system is set up. This seems to stem from the specific system configurations and understanding that are integral to these tools.

The successful installation and utilization of FragFold would be incredibly beneficial for our ongoing projects, particularly for screening using fragment-based development of therapeutic peptides with target protein-protein interactions. 

If needed, I can provide more detailed information on the issues encountered, which could help in diagnosing the problem more effectively.

Kind regards,

Namita Dube

**Comment by swanss** [comment]
Hi Namita,

It would help to have more details. Is it localcolabfold installation that is failing or the fragfold conda environment set up? My expectation is that it's the former, since that step is more complicated. 

(Sorry for the delayed response)

**Comment by swanss** [comment]
Hi, I've added details regarding installation to the README as well as a nextflow workflow. Please give those a shot if you're still trying to run FragFold.

**Comment by swanss** [comment]
Closing for now. If you or others have trouble with the new installation process, feel free to reopen.
